#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'fileutil.cpp',
		'geometry_intersection.cpp',
		'rect.cpp',
		'sdl_core.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='ymse',
		use=[
			'linear-algebra',
			'game-loop',
			'gl',
			'glew',
			'SDL',
		],
		includes=['../ymse'],
		export_includes=['..'],
	)
