#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'crashable_with_life.cpp',
		'food_generator.cpp',
		'food_item.cpp',
		'item_container.cpp',
		'movable.cpp',
		'player.cpp',
		'score_listener.cpp',
		'snake.cpp',
		'snake_direction_listener.cpp',
		'digesting_growth_policy.cpp',
		'growth_policy.cpp',
		'immediate_growth_policy.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='game',
		use=[
			'game-loop',
			'core',
			'board',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
