#!/bin/bash -e

./waf-make build_debug --targets=platform-pnacl_unstripped.bc

FINALIZE=~/Downloads/nacl_sdk/pepper_33/toolchain/linux_pnacl/bin64/pnacl-finalize
PEXE=build-pnacl/debug/src/platform-pnacl/platform-pnacl.pexe
BC=build-pnacl/debug/src/platform-pnacl/platform-pnacl_unstripped.bc

if [ "$BC" -nt "$PEXE" ]
then
	echo "Finalizing..."
	"$FINALIZE" -o "$PEXE" "$BC"
fi

exit $?
