#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'geometry_intersection.cpp',
		'rect.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='geometry',
		use=[
			'linear-algebra',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
