#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'main.cpp',
		'snygg_instance.cpp',
		'snygg_module.cpp',
		'urlloader_file_loader.cpp',
		'urlbuf.cpp',
		'iurlstream.cpp',
	]

	obj = bld.program(
		source=sources,
		target='platform-pnacl_unstripped.bc',
		use=[
			'board',
			'core',
			'fileutil',
			'game',
			'game-loop',
			'geometry',
			#'gl-raii',
			'image',
			#'image-gl',
			'linear-algebra',
			'lua-board-provider',
			#'opengl2-skins',
			#'platform-desktop-sdl',
			#'sdl-game-core',
			'segment',
			'skin',
			'svg-skin',
			'win32-util',

			'ppapi_cpp',
			'ppapi',
			'ppapi_gles2',

			'pthread',
		],
		lib=[],
		includes=[]
	)
