#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'metaballs_accumulator.cpp',
		'scalable_skin.cpp',
		'skin.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='skin',
		use=[
			'game-loop', # scalable_skin is a pixels_per_unit_listener
			'geometry',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
