#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'schematic_svg_skin.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='svg-skin',
		use=[
			'skin',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
