#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'board.cpp',
		'complex_polygon_triangulator.cpp',
		'complex_polygon_triangulator_gpc.cpp',
		'lua_vm.cpp',
		'segment_heap.cpp',
		'gpc/gpc.c',
	]

	obj = bld.stlib(
		source=sources,
		target='board',
		use=[
			'ymse',
			'lua',
			'luabind',

			'skin',
			'core',
			'segment',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
