#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'fileutil.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='fileutil',
		use=[],
		lib=[],
		includes=[],
		export_includes=["."],
	)
