#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	import platform

	platform_libs = []

	if platform.system() == 'Windows':
		platform_libs.append('User32')


	sources = [
		'main.cpp',
		'paths.cpp',
		'snygg.cpp',
	]

	obj = bld.program(
		source=sources,
		target='snygg',
		use=[
			'game',
			'board',
			'segment',
			'core',
			'skin',
			'ymse',

			'gl',
			'glew',
			'SDL',
			'SDLmain',
			'SDL_image',
			'imlib',
			'boost_filesystem',
			'boost_system',
		],
		lib=platform_libs,
		includes=[],
	)
