#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	import platform

	# waf names static libraries differently on windows
	lib_name_pattern = '%s'
	if platform.system() == 'Windows': lib_name_pattern = 'lib%s'

	sources = [
		'arc.cpp',
		'blood_pool.cpp',
		'board.cpp',
		'complex_polygon.cpp',
		'complex_polygon_triangulator.cpp',
		'complex_polygon_triangulator_gpc.cpp',
		'contour_segment.cpp',
		'digesting_growth_policy.cpp',
		'extender.cpp',
		'food_generator.cpp',
		'food_item.cpp',
		'gl_fbo.cpp',
		'growth_policy.cpp',
		'immediate_growth_policy.cpp',
		'intersectable_with_circle.cpp',
		'item.cpp',
		'item_container.cpp',
		'item_with_life.cpp',
		'line.cpp',
		'luamod/lua_vm.cpp',
		'main.cpp',
		'metaballs.cpp',
		'open_segment.cpp',
		'paths.cpp',
		'plain_skin.cpp',
		'player.cpp',
		'renderable.cpp',
		'scalable_skin.cpp',
		'schematic_skin.cpp',
		'scoped_bind_fbo.cpp',
		'scored_point.cpp',
		'segment_filter.cpp',
		'segment_heap.cpp',
		'segment_sequence.cpp',
		'skin.cpp',
		'snake.cpp',
		'snake_direction_listener.cpp',
		'snygg.cpp',
		'textured_skin.cpp',

		'gpc/gpc.c',

		'../external/downloads/luabind-0.9.1/src/class.cpp',
		'../external/downloads/luabind-0.9.1/src/class_info.cpp',
		'../external/downloads/luabind-0.9.1/src/class_registry.cpp',
		'../external/downloads/luabind-0.9.1/src/class_rep.cpp',
		'../external/downloads/luabind-0.9.1/src/create_class.cpp',
		'../external/downloads/luabind-0.9.1/src/error.cpp',
		'../external/downloads/luabind-0.9.1/src/exception_handler.cpp',
		'../external/downloads/luabind-0.9.1/src/function.cpp',
		'../external/downloads/luabind-0.9.1/src/inheritance.cpp',
		'../external/downloads/luabind-0.9.1/src/link_compatibility.cpp',
		'../external/downloads/luabind-0.9.1/src/object_rep.cpp',
		'../external/downloads/luabind-0.9.1/src/open.cpp',
		'../external/downloads/luabind-0.9.1/src/pcall.cpp',
		'../external/downloads/luabind-0.9.1/src/scope.cpp',
		'../external/downloads/luabind-0.9.1/src/stack_content_by_name.cpp',
		'../external/downloads/luabind-0.9.1/src/weak_ref.cpp',
		'../external/downloads/luabind-0.9.1/src/wrapper_base.cpp',
	]

	obj = bld.program(
		source=sources,
		target='snygg',
		use=['ymse', 'GL', 'glew', 'SDL', 'SDLmain', 'SDL_image', 'boost', 'lua', 'luabind', 'imlib'],
		lib=[lib_name_pattern % 'boost_filesystem', lib_name_pattern % 'boost_system'],
		includes=[],
	)
