#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	import platform

	lib_name_pattern = '%s'
	platform_libs = []

	if platform.system() == 'Windows':
		# waf names static libraries differently on windows for a misguided reason
		lib_name_pattern = 'lib%s'
		platform_libs.append('User32')

	sources = [
		'digesting_growth_policy.cpp',
		'food_generator.cpp',
		'food_item.cpp',
		'growth_policy.cpp',
		'immediate_growth_policy.cpp',
		'intersectable_with_circle.cpp',
		'item.cpp',
		'item_container.cpp',
		'item_with_life.cpp',
		'main.cpp',
		'paths.cpp',
		'player.cpp',
		'renderable.cpp',
		'snake.cpp',
		'snake_direction_listener.cpp',
		'snygg.cpp',

		'skin/complex_polygon.cpp',
		'skin/metaballs.cpp',
		'skin/plain_skin.cpp',
		'skin/scalable_skin.cpp',
		'skin/schematic_skin.cpp',
		'skin/skin.cpp',
		'skin/textured_skin.cpp',

		'skin/gl/gl_fbo.cpp',
		'skin/gl/opengl_resource.cpp',
		'skin/gl/scoped_bind_fbo.cpp',
		'skin/gl/shader_builder.cpp',
		'skin/gl/shader_configuration.cpp',
		'skin/gl/shader_program.cpp',

		'segment/arc.cpp',
		'segment/blood_pool.cpp',
		'segment/contour_segment.cpp',
		'segment/extender.cpp',
		'segment/line.cpp',
		'segment/open_segment.cpp',
		'segment/scored_point.cpp',
		'segment/segment_filter.cpp',
		'segment/segment_sequence.cpp',

		'board/board.cpp',
		'board/complex_polygon_triangulator.cpp',
		'board/complex_polygon_triangulator_gpc.cpp',
		'board/lua_vm.cpp',
		'board/segment_heap.cpp',
		'board/gpc/gpc.c',

		'../external/downloads/luabind-0.9.1/src/class.cpp',
		'../external/downloads/luabind-0.9.1/src/class_info.cpp',
		'../external/downloads/luabind-0.9.1/src/class_registry.cpp',
		'../external/downloads/luabind-0.9.1/src/class_rep.cpp',
		'../external/downloads/luabind-0.9.1/src/create_class.cpp',
		'../external/downloads/luabind-0.9.1/src/error.cpp',
		'../external/downloads/luabind-0.9.1/src/exception_handler.cpp',
		'../external/downloads/luabind-0.9.1/src/function.cpp',
		'../external/downloads/luabind-0.9.1/src/inheritance.cpp',
		'../external/downloads/luabind-0.9.1/src/link_compatibility.cpp',
		'../external/downloads/luabind-0.9.1/src/object_rep.cpp',
		'../external/downloads/luabind-0.9.1/src/open.cpp',
		'../external/downloads/luabind-0.9.1/src/pcall.cpp',
		'../external/downloads/luabind-0.9.1/src/scope.cpp',
		'../external/downloads/luabind-0.9.1/src/stack_content_by_name.cpp',
		'../external/downloads/luabind-0.9.1/src/weak_ref.cpp',
		'../external/downloads/luabind-0.9.1/src/wrapper_base.cpp',
	]

	obj = bld.program(
		source=sources,
		target='snygg',
		use=['ymse', 'GL', 'glew', 'SDL', 'SDLmain', 'SDL_image', 'boost', 'lua', 'luabind', 'imlib'],
		lib=[lib_name_pattern % 'boost_filesystem', lib_name_pattern % 'boost_system'] + platform_libs,
		includes=[],
	)
