#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	bld.recurse([
		'linear-algebra',
		'image',
		'image-gl',
		'gl-raii',
		'ymse',
		'skin',
		'segment',
		'core',
		'board',
		'game',
		'platform-desktop-sdl',
	])
