#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'copy.cpp',
	]

	obj = bld.stlib(
		source=sources,
		target='image-gl',
		use=[
			'image',
			'glew',
		],
		lib=[],
		includes=[],
		export_includes=["."],
	)
